[package]
name = "wasm-embed-aot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wasm-embed-aot"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
wasm-encoder = "0.243"
wasmparser = "0.243"
wit-bindgen = "0.49.0"
